import os
import requests
import subprocess
from pathlib import Path

class AutoDeployer:
    """Automatically create GitHub repo and deploy to Render"""
    
    def __init__(self, github_token: str = None, render_api_key: str = None):
        self.github_token = github_token or os.getenv('GITHUB_TOKEN')
        self.render_api_key = render_api_key or os.getenv('RENDER_API_KEY')
        self.github_api = "https://api.github.com"
        self.render_api = "https://api.render.com/v1"
    
    def deploy_app(self, project_dir: Path, app_name: str) -> dict:
        """Complete auto-deployment: GitHub + Render"""
        
        # 1. Create GitHub repo
        repo_url = self._create_github_repo(app_name)
        
        # 2. Push code to GitHub
        self._push_to_github(project_dir, repo_url)
        
        # 3. Deploy to Render
        render_urls = self._deploy_to_render(app_name, repo_url)
        
        return {
            "github_repo": repo_url,
            "frontend_url": render_urls['frontend'],
            "backend_url": render_urls['backend'],
            "status": "deployed"
        }
    
    def _create_github_repo(self, app_name: str) -> str:
        """Create GitHub repository"""
        
        headers = {
            "Authorization": f"token {self.github_token}",
            "Accept": "application/vnd.github.v3+json"
        }
        
        payload = {
            "name": app_name,
            "description": f"Generated by AutoDev - {app_name}",
            "private": False,
            "auto_init": False
        }
        
        response = requests.post(
            f"{self.github_api}/user/repos",
            headers=headers,
            json=payload
        )
        
        if response.ok:
            repo = response.json()
            return repo['clone_url']
        else:
            raise Exception(f"Failed to create GitHub repo: {response.text}")
    
    def _push_to_github(self, project_dir: Path, repo_url: str):
        """Push code to GitHub"""
        
        commands = [
            "git init",
            "git add .",
            'git commit -m "Initial commit by AutoDev"',
            f"git remote add origin {repo_url}",
            "git branch -M main",
            "git push -u origin main"
        ]
        
        for cmd in commands:
            subprocess.run(cmd, shell=True, cwd=str(project_dir), check=True)
    
    def _deploy_to_render(self, app_name: str, repo_url: str) -> dict:
        """Deploy to Render using Blueprint"""
        
        headers = {
            "Authorization": f"Bearer {self.render_api_key}",
            "Content-Type": "application/json"
        }
        
        # Render will auto-detect render.yaml in the repo
        payload = {
            "type": "blueprint",
            "repo": repo_url.replace(".git", ""),
            "autoDeploy": True
        }
        
        response = requests.post(
            f"{self.render_api}/blueprints",
            headers=headers,
            json=payload
        )
        
        if response.ok:
            blueprint = response.json()
            return {
                "frontend": f"https://{app_name}-frontend.onrender.com",
                "backend": f"https://{app_name}-backend.onrender.com"
            }
        else:
            raise Exception(f"Failed to deploy to Render: {response.text}")
